site_name: WikiHome 🏠
theme:
  name: material
  language: fr
  features:
    - navigation.expand
    - navigation.top
    - search.suggest
    - content.code.copy
nav:
  - Accueil: index.md
  - Saisonnier:
    - Montage Sapin: guides/saisonnier/montage_sapin.md
    - Specs Sapin: guides/saisonnier/specs_sapin.md
  - Cuisine:
    - Cuisson Oeufs: guides/cuisine/cuisson_oeufs.md
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list